modLoader = "javafml"
loaderVersion = "[34,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "phantomconfig"
version = "${version}"
displayName = "Phantom Config"
authors = "IAmSneak"
description = '''
Modify phantom spawning to be less annoying
'''
#logoFile = ""

[[dependencies.phantomconfig]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.phantomconfig]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,)"
ordering = "NONE"
side = "BOTH"